#!/bin/bash

if [ -z "$DISPLAY" ]
then
  exec emacs "$@"
fi

if [ -n "$EMACS_SERVER_FILE" ]
then
  exec emacsclient --create-frame --alternate-editor="" "$@"
else
  ws=$(i3-msg -t get_workspaces | jq -r 'map(select(.focused))[0].name' | sed 's,^[^:]*:\s*,,g')
  exec emacsclient --socket-name=$ws --create-frame --alternate-editor="" "$@"
fi
