[main]
font=Bitstream Vera Sans Mono:size=8
# To match URxvt color behavior.
bold-text-in-bright=palette-based

[key-bindings]
show-urls-launch=Alt+u
search-start=Alt+s
spawn-terminal=Super+o

[url]
launch=google-chrome ${url}

[bell]
urgent=yes

[scrollback]
lines=32768

# Colors matching my old URxvt theme.
[colors]
background=000000
# lightgrey in X11 is RGB (211, 211, 211)
foreground=d3d3d3
regular0=2e3436
regular1=cc0000
regular2=4e9a06
regular3=c4a000
regular4=3465a4
regular5=ef33c0
regular6=04b5b8
regular7=d3d7cf
bright0=555753
bright1=ef2929
bright2=8ae234
bright3=fce94f
bright4=729fcf
bright5=ee38da
bright6=34e2e2
bright7=eeeeec
